import { Response } from 'express';
import crypto from 'crypto';
import { supabase } from '../config/supabase';
import { AuthRequest } from '../types';
import { logAuditEvent } from '../services/auditService';

interface ReportSettings {
  gradeConfig: Array<{ grade: string; min: number; max: number; remark: string }>;
  thresholds: { pass: number; improve: number; strength: number };
  branding: {
    reportTitle: string;
    subtitle: string;
    schoolName: string;
    directorName: string;
    directorTitle: string;
    footerNote: string;
  };
}

const DEFAULT_SETTINGS: ReportSettings = {
  gradeConfig: [
    { grade: 'A+', min: 90, max: 100, remark: 'Excellent' },
    { grade: 'A', min: 80, max: 89, remark: 'Very Good' },
    { grade: 'B', min: 70, max: 79, remark: 'Good' },
    { grade: 'C', min: 60, max: 69, remark: 'Satisfactory' },
    { grade: 'D', min: 50, max: 59, remark: 'Needs Improvement' },
    { grade: 'F', min: 0, max: 49, remark: 'Unsatisfactory' },
  ],
  thresholds: { pass: 50, improve: 60, strength: 75 },
  branding: {
    reportTitle: 'STUDENT ACADEMIC PERFORMANCE REPORT',
    subtitle: 'Academic Performance & Learning Progress',
    schoolName: '',
    directorName: '',
    directorTitle: 'Headteacher',
    footerNote: 'This report was generated by the PASSCO learning platform.',
  },
};

function clientIp(req: AuthRequest): string {
  const fwd = req.headers['x-forwarded-for'];
  if (typeof fwd === 'string' && fwd) return fwd.split(',')[0].trim();
  return req.ip || '';
}

const VERIFY_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

function randomVerifyCode(): string {
  let out = 'PASSCO-VRF-';
  const bytes = crypto.randomBytes(8);
  for (let i = 0; i < 8; i++) out += VERIFY_CHARS[bytes[i] % VERIFY_CHARS.length];
  return out;
}

async function generateUniqueReportNumber(year: string): Promise<string> {
  const prefix = `PASSCO-RPT-${year.replace(/\D/g, '').slice(0, 4) || String(new Date().getFullYear())}-`;
  for (let attempt = 0; attempt < 5; attempt++) {
    const candidate = `${prefix}${String(Math.floor(100000 + Math.random() * 900000))}`;
    const { data } = await supabase.from('report_cards').select('id').eq('report_number', candidate).maybeSingle();
    if (!data) return candidate;
  }
  return `${prefix}${Date.now().toString().slice(-6)}`;
}

async function generateUniqueVerificationCode(): Promise<string> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const candidate = randomVerifyCode();
    const { data } = await supabase.from('report_cards').select('id').eq('verification_code', candidate).maybeSingle();
    if (!data) return candidate;
  }
  return randomVerifyCode();
}

function serialize(row: Record<string, unknown>) {
  return {
    id: row.id,
    userId: row.user_id,
    reportNumber: row.report_number,
    verificationCode: row.verification_code,
    academicYear: row.academic_year,
    term: row.term,
    periodLabel: row.period_label,
    periodStart: row.period_start,
    periodEnd: row.period_end,
    overallScore: Number(row.overall_score || 0),
    overallGrade: row.overall_grade,
    overallRemark: row.overall_remark,
    status: row.status,
    dataSnapshot: row.data_snapshot,
    profilePhotoSnapshotUrl: row.profile_photo_snapshot_url || '',
    generatedAt: row.generated_at,
    generatedBy: row.generated_by,
  };
}

export interface GenerateReportRecordInput {
  targetUserId: string;
  actorUserId?: string;
  body: Record<string, unknown>;
  ip?: string;
}

export async function generateReportRecord(input: GenerateReportRecordInput): Promise<ReturnType<typeof serialize>> {
  const { targetUserId, actorUserId, body: b, ip } = input;

  const academicYear = String(b.academicYear || String(new Date().getFullYear()));
  const term = String(b.term || 'Full Year');

  const { data: targetUser } = await supabase.from('users').select('name').eq('id', targetUserId).maybeSingle();
  if (!targetUser) throw new Error('Student not found');

  const reportNumber = await generateUniqueReportNumber(academicYear);
  const verificationCode = await generateUniqueVerificationCode();

  const overallScore = Math.max(0, Math.min(100, Number(b.overallScore ?? 0)));
  const overallGrade = String(b.overallGrade || 'F');
  const overallRemark = String(b.overallRemark || '');

  await supabase
    .from('report_cards')
    .update({ status: 'superseded' })
    .eq('user_id', targetUserId)
    .eq('academic_year', academicYear)
    .eq('term', term)
    .eq('status', 'current');

  const { data: record, error } = await supabase
    .from('report_cards')
    .insert({
      user_id: targetUserId,
      report_number: reportNumber,
      verification_code: verificationCode,
      academic_year: academicYear,
      term,
      period_label: String(b.periodLabel || ''),
      period_start: b.periodStart || null,
      period_end: b.periodEnd || null,
      overall_score: overallScore,
      overall_grade: overallGrade,
      overall_remark: overallRemark,
      data_snapshot: b.dataSnapshot || {},
      profile_photo_snapshot_url: String(b.profilePhotoSnapshotUrl || ''),
      generated_by: actorUserId,
    })
    .select()
    .single();

  if (error) throw error;

  await logAuditEvent({
    userId: actorUserId,
    action: 'report_generated',
    entityType: 'report_card',
    entityId: record.id,
    ipAddress: ip,
    details: { userId: targetUserId, academicYear, term, overallScore, reportNumber },
  });

  return serialize(record);
}

async function createReport(req: AuthRequest, res: Response, adminUserId?: string): Promise<void> {
  const targetUserId = adminUserId || req.user?.id;
  if (!targetUserId) {
    res.status(401).json({ message: 'Unauthorized' });
    return;
  }

  try {
    const record = await generateReportRecord({
      targetUserId,
      actorUserId: req.user?.id,
      body: (req.body || {}) as Record<string, unknown>,
      ip: clientIp(req),
    });
    res.status(201).json({ report: record });
  } catch (error) {
    console.error('Create report card error:', error);
    res.status(500).json({ message: 'Your report could not be generated. Please try again.' });
  }
}

export async function createReportCard(req: AuthRequest, res: Response): Promise<void> {
  await createReport(req, res);
}

export async function createReportCardForUser(req: AuthRequest, res: Response): Promise<void> {
  const userId = String((req.body as Record<string, unknown>)?.userId || '');
  if (!userId) {
    res.status(400).json({ message: 'Student is required' });
    return;
  }
  await createReport(req, res, userId);
}

export async function getMyReportCards(req: AuthRequest, res: Response): Promise<void> {
  try {
    const { data } = await supabase
      .from('report_cards')
      .select('*')
      .eq('user_id', req.user?.id)
      .order('generated_at', { ascending: false });

    res.json({ reports: (data || []).map(serialize) });
  } catch {
    res.status(500).json({ message: 'Failed to load reports' });
  }
}

export async function listStudentReports(req: AuthRequest, res: Response): Promise<void> {
  try {
    const userId = String(req.query.userId || '');
    if (!userId) {
      res.status(400).json({ message: 'userId is required' });
      return;
    }
    const { data } = await supabase
      .from('report_cards')
      .select('*')
      .eq('user_id', userId)
      .order('generated_at', { ascending: false });

    res.json({ reports: (data || []).map(serialize) });
  } catch {
    res.status(500).json({ message: 'Failed to load reports' });
  }
}

export async function getReportCard(req: AuthRequest, res: Response): Promise<void> {
  try {
    const id = String(req.params.id || '');
    const { data } = await supabase.from('report_cards').select('*').eq('id', id).maybeSingle();
    if (!data) {
      res.status(404).json({ message: 'Report not found' });
      return;
    }
    if (data.user_id !== req.user?.id && req.user?.role !== 'admin') {
      res.status(403).json({ message: 'You do not have access to this report' });
      return;
    }
    res.json({ report: serialize(data) });
  } catch {
    res.status(500).json({ message: 'Failed to load report' });
  }
}

export async function deleteReportCard(req: AuthRequest, res: Response): Promise<void> {
  try {
    const id = String(req.params.id || '');
    const { data } = await supabase.from('report_cards').select('id, user_id').eq('id', id).maybeSingle();
    if (!data) {
      res.status(404).json({ message: 'Report not found' });
      return;
    }
    if (data.user_id !== req.user?.id && req.user?.role !== 'admin') {
      res.status(403).json({ message: 'You do not have access to this report' });
      return;
    }

    const { error } = await supabase.from('report_cards').update({ status: 'void' }).eq('id', id);
    if (error) throw error;

    await logAuditEvent({
      userId: req.user?.id,
      action: 'report_deleted',
      entityType: 'report_card',
      entityId: id,
      ipAddress: clientIp(req),
    });

    res.json({ message: 'Report deleted' });
  } catch {
    res.status(500).json({ message: 'Failed to delete report' });
  }
}

export async function verifyReport(req: AuthRequest, res: Response): Promise<void> {
  try {
    const code = String(req.params.code || '');
    const { data } = await supabase
      .from('report_cards')
      .select('*, users(name)')
      .eq('verification_code', code)
      .neq('status', 'void')
      .maybeSingle();

    if (!data) {
      res.json({ found: false });
      return;
    }

    const fullName: string = (data.users as { name?: string } | null)?.name || '';
    const parts = fullName.trim().split(/\s+/);
    const masked =
      parts.length >= 2
        ? `${parts[0].charAt(0)}. ${parts.slice(1).join(' ')}`
        : parts[0]?.charAt(0).toUpperCase() || 'PASSCO Student';

    res.json({
      found: true,
      reportNumber: data.report_number,
      academicYear: data.academic_year,
      term: data.term,
      overallGrade: data.overall_grade,
      overallScore: Number(data.overall_score || 0),
      generatedAt: data.generated_at,
      studentNameMasked: masked,
    });
  } catch {
    res.status(500).json({ found: false });
  }
}

export async function getReportSettings(req: AuthRequest, res: Response): Promise<void> {
  try {
    const { data } = await supabase.from('platform_settings').select('value').eq('key', 'report').maybeSingle();
    res.json({ settings: (data?.value as ReportSettings) || DEFAULT_SETTINGS });
  } catch {
    res.json({ settings: DEFAULT_SETTINGS });
  }
}

export async function updateReportSettings(req: AuthRequest, res: Response): Promise<void> {
  try {
    const current = await getSettings();
    const incoming = (req.body || {}) as Partial<ReportSettings>;

    const gradeIn = incoming.gradeConfig;
    const gradeConfig = Array.isArray(gradeIn)
      ? gradeIn
          .filter((g) => g && typeof g.grade === 'string')
          .map((g) => ({
            grade: String(g.grade).toUpperCase(),
            min: Math.max(0, Math.min(100, Number(g.min || 0))),
            max: Math.max(0, Math.min(100, Number(g.max ?? 100))),
            remark: String(g.remark || ''),
          }))
          .sort((a, b) => b.min - a.min)
      : current.gradeConfig;

    const thresholds = incoming.thresholds && typeof incoming.thresholds === 'object'
      ? {
          pass: Math.max(0, Math.min(100, Number(incoming.thresholds.pass ?? current.thresholds.pass))),
          improve: Math.max(0, Math.min(100, Number(incoming.thresholds.improve ?? current.thresholds.improve))),
          strength: Math.max(0, Math.min(100, Number(incoming.thresholds.strength ?? current.thresholds.strength))),
        }
      : current.thresholds;

    const branding = incoming.branding && typeof incoming.branding === 'object'
      ? {
          reportTitle: String(incoming.branding.reportTitle ?? current.branding.reportTitle),
          subtitle: String(incoming.branding.subtitle ?? current.branding.subtitle),
          schoolName: String(incoming.branding.schoolName ?? current.branding.schoolName),
          directorName: String(incoming.branding.directorName ?? current.branding.directorName),
          directorTitle: String(incoming.branding.directorTitle ?? current.branding.directorTitle),
          footerNote: String(incoming.branding.footerNote ?? current.branding.footerNote),
        }
      : current.branding;

    const next: ReportSettings = { gradeConfig, thresholds, branding };
    const { error } = await supabase
      .from('platform_settings')
      .upsert({ key: 'report', value: next, updated_at: new Date().toISOString(), updated_by: req.user?.id });

    if (error) throw error;

    await logAuditEvent({
      userId: req.user?.id,
      action: 'report_settings_updated',
      entityType: 'report_settings',
      entityId: 'report',
      ipAddress: clientIp(req),
    });

    res.json({ settings: next });
  } catch {
    res.status(500).json({ message: 'Failed to save report settings' });
  }
}

export async function getSettings(): Promise<ReportSettings> {
  const { data } = await supabase.from('platform_settings').select('value').eq('key', 'report').maybeSingle();
  return (data?.value as ReportSettings) || DEFAULT_SETTINGS;
}