-- =============================================================================
-- PASSCO STUDENT ACADEMIC REPORT CARDS MIGRATION
--
-- Adds:
--   * report_cards        - generated student academic performance report documents
--   * platform_settings  - key/value app configuration (report grade config & branding)
--
-- WHERE TO RUN: Supabase SQL Editor  (idempotent - safe to re-run)
-- =============================================================================

CREATE TABLE IF NOT EXISTS report_cards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  report_number TEXT NOT NULL UNIQUE,
  verification_code TEXT NOT NULL UNIQUE,
  academic_year TEXT NOT NULL DEFAULT '',
  term TEXT NOT NULL DEFAULT 'Full Year',
  period_label TEXT NOT NULL DEFAULT '',
  period_start DATE,
  period_end DATE,
  overall_score NUMERIC(5,1) NOT NULL DEFAULT 0,
  overall_grade TEXT NOT NULL DEFAULT 'F',
  overall_remark TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'current' CHECK (status IN ('current', 'superseded', 'void')),
  data_snapshot JSONB NOT NULL DEFAULT '{}',
  profile_photo_snapshot_url TEXT DEFAULT '',
  data_snapshot_version INTEGER NOT NULL DEFAULT 1,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  generated_by UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_report_cards_user ON report_cards (user_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_report_cards_user_period ON report_cards (user_id, academic_year, term);
CREATE INDEX IF NOT EXISTS idx_report_cards_verification ON report_cards (verification_code);
CREATE INDEX IF NOT EXISTS idx_report_cards_status ON report_cards (status);

CREATE TABLE IF NOT EXISTS platform_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO platform_settings (key, value)
VALUES (
  'report',
  '{
    "gradeConfig": [
      {"grade":"A+","min":90,"max":100,"remark":"Excellent"},
      {"grade":"A","min":80,"max":89,"remark":"Very Good"},
      {"grade":"B","min":70,"max":79,"remark":"Good"},
      {"grade":"C","min":60,"max":69,"remark":"Satisfactory"},
      {"grade":"D","min":50,"max":59,"remark":"Needs Improvement"},
      {"grade":"F","min":0,"max":49,"remark":"Unsatisfactory"}
    ],
    "thresholds": { "pass": 50, "improve": 60, "strength": 75 },
    "branding": {
      "reportTitle": "STUDENT ACADEMIC PERFORMANCE REPORT",
      "subtitle": "Academic Performance & Learning Progress",
      "schoolName": "",
      "directorName": "",
      "directorTitle": "Headteacher",
      "footerNote": "This report was generated by the PASSCO learning platform."
    }
  }'
)
ON CONFLICT (key) DO NOTHING;

-- RLS - permissive policy matching the rest of the schema (ownership enforced in controllers)
ALTER TABLE report_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for authenticated" ON report_cards FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON platform_settings FOR ALL USING (true) WITH CHECK (true);